package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
)

// nginxConfig generates an nginx reverse-proxy config for the edge node dashboard.
func nginxConfig(domain string, apiPort int) string {
	serverName := "_" // catch-all if no domain
	if domain != "" {
		serverName = domain
	}

	var b strings.Builder
	b.WriteString("# GoVault Edge Node — nginx reverse proxy\n")
	b.WriteString("# Linux:   /etc/nginx/sites-available/edgenode\n")
	b.WriteString("# Windows: C:\\nginx\\conf\\sites\\edgenode.conf\n\n")
	fmt.Fprintf(&b, "server {\n")
	fmt.Fprintf(&b, "    listen 80;\n")
	fmt.Fprintf(&b, "    server_name %s;\n\n", serverName)
	fmt.Fprintf(&b, "    location / {\n")
	fmt.Fprintf(&b, "        proxy_pass         http://127.0.0.1:%d;\n", apiPort)
	fmt.Fprintf(&b, "        proxy_http_version 1.1;\n")
	fmt.Fprintf(&b, "        proxy_set_header   Host              $host;\n")
	fmt.Fprintf(&b, "        proxy_set_header   X-Real-IP         $remote_addr;\n")
	fmt.Fprintf(&b, "        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;\n")
	fmt.Fprintf(&b, "        proxy_set_header   X-Forwarded-Proto $scheme;\n")
	fmt.Fprintf(&b, "        proxy_read_timeout 86400;\n")
	fmt.Fprintf(&b, "    }\n")
	fmt.Fprintf(&b, "}\n")
	return b.String()
}

// nginxSetupScriptLinux generates a bash script that installs nginx + certbot,
// drops the config in sites-available, and optionally issues an SSL cert.
func nginxSetupScriptLinux(domain string, nginxConfPath string) string {
	var b strings.Builder
	b.WriteString("#!/bin/bash\n")
	b.WriteString("# GoVault Edge Node — nginx + SSL setup (Linux)\n")
	b.WriteString("# Generated by --init. Safe to re-run.\n")
	b.WriteString("set -e\n\n")

	b.WriteString("echo\n")
	b.WriteString("echo '  Installing nginx and certbot...'\n")
	b.WriteString("apt-get update -qq\n")
	b.WriteString("apt-get install -y nginx certbot python3-certbot-nginx\n\n")

	b.WriteString("echo '  Installing nginx config...'\n")
	fmt.Fprintf(&b, "cp %q /etc/nginx/sites-available/edgenode\n", nginxConfPath)
	b.WriteString("ln -sf /etc/nginx/sites-available/edgenode /etc/nginx/sites-enabled/edgenode\n")
	b.WriteString("rm -f /etc/nginx/sites-enabled/default\n\n")

	b.WriteString("echo '  Testing nginx config...'\n")
	b.WriteString("nginx -t\n")
	b.WriteString("systemctl enable nginx\n")
	b.WriteString("systemctl restart nginx\n\n")

	if domain != "" {
		fmt.Fprintf(&b, "echo '  Obtaining SSL certificate for %s...'\n", domain)
		fmt.Fprintf(&b, "certbot --nginx -d %s --non-interactive --agree-tos --register-unsafely-without-email --redirect\n\n", domain)
		b.WriteString("echo\n")
		fmt.Fprintf(&b, "echo '  ✓ Done! Dashboard: https://%s'\n", domain)
	} else {
		b.WriteString("echo\n")
		b.WriteString("echo '  ✓ Done! Dashboard: http://<your-server-ip>'\n")
	}
	b.WriteString("echo\n")
	return b.String()
}

// nginxSetupScriptWindows generates a PowerShell script that installs nginx
// (via Chocolatey or direct download), drops the config, and starts/reloads.
// SSL on Windows requires win-acme; instructions are printed at the end.
func nginxSetupScriptWindows(domain string, nginxConfPath string) string {
	var b strings.Builder
	b.WriteString("# GoVault Edge Node — nginx setup (Windows)\n")
	b.WriteString("# Run as Administrator in PowerShell\n")
	b.WriteString("# Generated by --init. Safe to re-run.\n\n")

	b.WriteString("$ErrorActionPreference = 'Stop'\n\n")

	// Detect existing nginx
	b.WriteString("# Locate nginx (installed or fresh download)\n")
	b.WriteString("$nginxExe = $null\n")
	b.WriteString("try { $nginxExe = (Get-Command nginx -ErrorAction Stop).Source } catch {}\n\n")

	// Install if missing
	b.WriteString("if (-not $nginxExe) {\n")
	b.WriteString("    if (Get-Command choco -ErrorAction SilentlyContinue) {\n")
	b.WriteString("        Write-Host '  Installing nginx via Chocolatey...'\n")
	b.WriteString("        choco install nginx -y --no-progress\n")
	b.WriteString("        $nginxExe = (Get-Command nginx).Source\n")
	b.WriteString("    } else {\n")
	b.WriteString("        Write-Host '  Downloading nginx 1.27.4...'\n")
	b.WriteString("        $zip = 'nginx-1.27.4.zip'\n")
	b.WriteString("        Invoke-WebRequest 'https://nginx.org/download/nginx-1.27.4.zip' -OutFile $zip\n")
	b.WriteString("        Expand-Archive $zip -DestinationPath 'C:\\' -Force\n")
	b.WriteString("        if (Test-Path 'C:\\nginx') { Remove-Item 'C:\\nginx' -Recurse -Force }\n")
	b.WriteString("        Rename-Item 'C:\\nginx-1.27.4' 'C:\\nginx'\n")
	b.WriteString("        $nginxExe = 'C:\\nginx\\nginx.exe'\n")
	b.WriteString("        $env:PATH += ';C:\\nginx'\n")
	b.WriteString("        [Environment]::SetEnvironmentVariable('PATH', $env:PATH, 'Machine')\n")
	b.WriteString("    }\n")
	b.WriteString("}\n\n")

	// Find nginx conf dir and ensure sites/ subdir + include exists
	b.WriteString("$nginxDir  = Split-Path $nginxExe\n")
	b.WriteString("$confDir   = Join-Path $nginxDir 'conf\\sites'\n")
	b.WriteString("New-Item -ItemType Directory -Force -Path $confDir | Out-Null\n\n")

	b.WriteString("# Ensure nginx.conf includes sites/*.conf\n")
	b.WriteString("$mainConf    = Join-Path $nginxDir 'conf\\nginx.conf'\n")
	b.WriteString("$mainContent = Get-Content $mainConf -Raw\n")
	b.WriteString("if ($mainContent -notmatch 'sites/') {\n")
	b.WriteString("    $mainContent = $mainContent -replace 'http \\{', \"http {`n    include sites/*.conf;\"\n")
	b.WriteString("    $mainContent | Set-Content $mainConf -Encoding UTF8\n")
	b.WriteString("    Write-Host '  Patched nginx.conf to include sites/*.conf'\n")
	b.WriteString("}\n\n")

	// Drop the config
	b.WriteString("Write-Host '  Installing edge node nginx config...'\n")
	fmt.Fprintf(&b, "Copy-Item %q -Destination (Join-Path $confDir 'edgenode.conf') -Force\n\n", nginxConfPath)

	// Test + start/reload
	b.WriteString("Write-Host '  Testing nginx config...'\n")
	b.WriteString("& $nginxExe -t\n\n")
	b.WriteString("$running = Get-Process nginx -ErrorAction SilentlyContinue\n")
	b.WriteString("if ($running) {\n")
	b.WriteString("    Write-Host '  Reloading nginx...'\n")
	b.WriteString("    & $nginxExe -s reload\n")
	b.WriteString("} else {\n")
	b.WriteString("    Write-Host '  Starting nginx...'\n")
	b.WriteString("    Start-Process $nginxExe -WorkingDirectory $nginxDir\n")
	b.WriteString("}\n\n")

	// Optionally register as a Windows service via NSSM hint
	b.WriteString("Write-Host ''\n")
	if domain != "" {
		fmt.Fprintf(&b, "Write-Host '  ✓ nginx configured. Dashboard (HTTP): http://%s'\n", domain)
		b.WriteString("Write-Host ''\n")
		b.WriteString("Write-Host '  For HTTPS, install win-acme and run:'\n")
		b.WriteString("Write-Host '    https://www.win-acme.com/'\n")
		fmt.Fprintf(&b, "Write-Host '    wacs --source manual --host %s --installation nginx'\n", domain)
	} else {
		b.WriteString("Write-Host '  ✓ nginx configured. Dashboard: http://localhost'\n")
	}
	b.WriteString("Write-Host ''\n")
	b.WriteString("Write-Host '  Tip: to run nginx as a Windows service, install NSSM:'\n")
	b.WriteString("Write-Host '    https://nssm.cc  ->  nssm install nginx'\n")
	b.WriteString("Write-Host ''\n")
	return b.String()
}

// RunNginxSetup generates nginx config + setup script and (on Linux) runs it.
// Returns combined output text for display in the admin panel.
func RunNginxSetup(domain string, apiPort int, dataDir string) (string, error) {
	var out strings.Builder

	if err := os.MkdirAll(dataDir, 0755); err != nil {
		return "", fmt.Errorf("create data dir: %w", err)
	}

	// Write nginx config.
	nginxConfPath := filepath.Join(dataDir, "nginx-edgenode.conf")
	if err := os.WriteFile(nginxConfPath, []byte(nginxConfig(domain, apiPort)), 0644); err != nil {
		return "", fmt.Errorf("write nginx config: %w", err)
	}
	out.WriteString("✓ nginx config written: " + nginxConfPath + "\n")

	switch runtime.GOOS {
	case "linux":
		scriptPath := filepath.Join(dataDir, "setup-nginx.sh")
		script := nginxSetupScriptLinux(domain, nginxConfPath)
		if err := os.WriteFile(scriptPath, []byte(script), 0755); err != nil {
			return out.String(), fmt.Errorf("write setup script: %w", err)
		}
		out.WriteString("✓ setup script written: " + scriptPath + "\n")
		out.WriteString("Running nginx setup (sudo required)...\n\n")

		cmd := exec.Command("sudo", "bash", scriptPath)
		var combined strings.Builder
		cmd.Stdout = &combined
		cmd.Stderr = &combined
		err := cmd.Run()
		out.WriteString(combined.String())
		if err != nil {
			return out.String(), fmt.Errorf("nginx setup failed: %w", err)
		}
		return out.String(), nil

	default:
		// Windows / other: generate script and return instructions.
		scriptPath := filepath.Join(dataDir, "setup-nginx.ps1")
		script := nginxSetupScriptWindows(domain, nginxConfPath)
		if err := os.WriteFile(scriptPath, []byte(script), 0644); err != nil {
			return out.String(), fmt.Errorf("write PowerShell script: %w", err)
		}
		out.WriteString("✓ PowerShell script written: " + scriptPath + "\n\n")
		out.WriteString("Automatic execution is not supported on Windows.\n")
		out.WriteString("Run the following in an Administrator PowerShell:\n\n")
		out.WriteString("  Set-ExecutionPolicy Bypass -Scope Process\n")
		out.WriteString("  & '" + scriptPath + "'\n")
		if domain != "" {
			out.WriteString("\nFor HTTPS after running the script, install win-acme:\n")
			out.WriteString("  https://www.win-acme.com/\n")
			out.WriteString("  wacs --source manual --host " + domain + " --installation nginx\n")
		}
		return out.String(), nil
	}
}

// runNginxScript executes the Linux nginx setup script with sudo.
func runNginxScript(path string) {
	fmt.Println()
	fmt.Println("  Running nginx setup (sudo required)...")
	fmt.Println()
	cmd := exec.Command("sudo", "bash", path)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Stdin = os.Stdin
	if err := cmd.Run(); err != nil {
		fmt.Fprintf(os.Stderr, "\n  ERROR: nginx setup failed: %v\n", err)
		fmt.Fprintf(os.Stderr, "  Run manually: sudo bash %s\n\n", path)
	}
}
