// AUTO-GENERATED by scripts/gen-web-shim.mjs — do not edit.
// Mirrors the bound appcore.App methods as RPC calls for the web build.
import { rpc } from './rpc.js';

export function ClearRejectedShares(...args) { return rpc('ClearRejectedShares', args); }
export function ClearStatistics(...args) { return rpc('ClearStatistics', args); }
export function CompactDatabase(...args) { return rpc('CompactDatabase', args); }
export function ConfigureMiner(...args) { return rpc('ConfigureMiner', args); }
export function ConnectNode(...args) { return rpc('ConnectNode', args); }
export function DetectNode(...args) { return rpc('DetectNode', args); }
export function GetCoinList(...args) { return rpc('GetCoinList', args); }
export function GetConfig(...args) { return rpc('GetConfig', args); }
export function GetDashboardStats(...args) { return rpc('GetDashboardStats', args); }
export function GetDatabaseInfo(...args) { return rpc('GetDatabaseInfo', args); }
export function GetFleetOverview(...args) { return rpc('GetFleetOverview', args); }
export function GetHashrateHistory(...args) { return rpc('GetHashrateHistory', args); }
export function GetMinerHashrateHistory(...args) { return rpc('GetMinerHashrateHistory', args); }
export function GetMiners(...args) { return rpc('GetMiners', args); }
export function GetMiningMode(...args) { return rpc('GetMiningMode', args); }
export function GetNodeStatus(...args) { return rpc('GetNodeStatus', args); }
export function GetProxyDiagnostics(...args) { return rpc('GetProxyDiagnostics', args); }
export function GetRecentLogs(...args) { return rpc('GetRecentLogs', args); }
export function GetStratumURL(...args) { return rpc('GetStratumURL', args); }
export function GetUpstreamStatus(...args) { return rpc('GetUpstreamStatus', args); }
export function IsStratumRunning(...args) { return rpc('IsStratumRunning', args); }
export function OnStartup(...args) { return rpc('OnStartup', args); }
export function ReconnectMiners(...args) { return rpc('ReconnectMiners', args); }
export function ScanForMiners(...args) { return rpc('ScanForMiners', args); }
export function SetHost(...args) { return rpc('SetHost', args); }
export function SetLogLevel(...args) { return rpc('SetLogLevel', args); }
export function ShowWindow(...args) { return rpc('ShowWindow', args); }
export function Shutdown(...args) { return rpc('Shutdown', args); }
export function StartStratum(...args) { return rpc('StartStratum', args); }
export function StopStratum(...args) { return rpc('StopStratum', args); }
export function TestNodeConnection(...args) { return rpc('TestNodeConnection', args); }
export function TestUpstreamConnection(...args) { return rpc('TestUpstreamConnection', args); }
export function UpdateConfig(...args) { return rpc('UpdateConfig', args); }
export function ValidateAddress(...args) { return rpc('ValidateAddress', args); }
