// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearRejectedShares() {
  return window['go']['main']['App']['ClearRejectedShares']();
}

export function ConfigureMiner(arg1) {
  return window['go']['main']['App']['ConfigureMiner'](arg1);
}

export function ConnectNode() {
  return window['go']['main']['App']['ConnectNode']();
}

export function DetectNode(arg1) {
  return window['go']['main']['App']['DetectNode'](arg1);
}

export function GetCoinList() {
  return window['go']['main']['App']['GetCoinList']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDashboardStats() {
  return window['go']['main']['App']['GetDashboardStats']();
}

export function GetDatabaseInfo() {
  return window['go']['main']['App']['GetDatabaseInfo']();
}

export function GetFleetOverview() {
  return window['go']['main']['App']['GetFleetOverview']();
}

export function GetHashrateHistory(arg1) {
  return window['go']['main']['App']['GetHashrateHistory'](arg1);
}

export function GetMinerHashrateHistory(arg1) {
  return window['go']['main']['App']['GetMinerHashrateHistory'](arg1);
}

export function GetMiners() {
  return window['go']['main']['App']['GetMiners']();
}

export function GetMiningMode() {
  return window['go']['main']['App']['GetMiningMode']();
}

export function GetNodeStatus() {
  return window['go']['main']['App']['GetNodeStatus']();
}

export function GetRecentLogs(arg1) {
  return window['go']['main']['App']['GetRecentLogs'](arg1);
}

export function GetStratumURL() {
  return window['go']['main']['App']['GetStratumURL']();
}

export function GetUpstreamStatus() {
  return window['go']['main']['App']['GetUpstreamStatus']();
}

export function IsStratumRunning() {
  return window['go']['main']['App']['IsStratumRunning']();
}

export function ReconnectMiners() {
  return window['go']['main']['App']['ReconnectMiners']();
}

export function ScanForMiners() {
  return window['go']['main']['App']['ScanForMiners']();
}

export function SetLogLevel(arg1) {
  return window['go']['main']['App']['SetLogLevel'](arg1);
}

export function StartStratum() {
  return window['go']['main']['App']['StartStratum']();
}

export function StopStratum() {
  return window['go']['main']['App']['StopStratum']();
}

export function TestNodeConnection(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['TestNodeConnection'](arg1, arg2, arg3, arg4, arg5);
}

export function TestUpstreamConnection(arg1, arg2, arg3) {
  return window['go']['main']['App']['TestUpstreamConnection'](arg1, arg2, arg3);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function ValidateAddress(arg1, arg2) {
  return window['go']['main']['App']['ValidateAddress'](arg1, arg2);
}
