// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {update} from '../models';
import {config} from '../models';
import {miner} from '../models';
import {appcore} from '../models';
import {logger} from '../models';
import {context} from '../models';

export function ApplyUpdate():Promise<void>;

export function CheckForUpdate():Promise<update.Info>;

export function ClearRejectedShares():Promise<number>;

export function ClearStatistics():Promise<number>;

export function CompactDatabase():Promise<Record<string, any>>;

export function ConfigureMiner(arg1:string):Promise<void>;

export function ConnectNode():Promise<Record<string, any>>;

export function DetectNode(arg1:string):Promise<Record<string, any>>;

export function GetCoinList():Promise<Array<Record<string, any>>>;

export function GetConfig():Promise<config.Config>;

export function GetDashboardStats():Promise<miner.DashboardStats>;

export function GetDatabaseInfo():Promise<Record<string, any>>;

export function GetFleetOverview():Promise<appcore.FleetOverview>;

export function GetHashrateHistory(arg1:string):Promise<Array<miner.HashratePoint>>;

export function GetMinerHashrateHistory(arg1:string):Promise<Array<miner.HashratePoint>>;

export function GetMiners():Promise<Array<miner.MinerInfo>>;

export function GetMiningMode():Promise<string>;

export function GetNodeStatus():Promise<Record<string, any>>;

export function GetProxyDiagnostics():Promise<Record<string, any>>;

export function GetRecentLogs(arg1:number):Promise<Array<logger.LogEntry>>;

export function GetStratumURL():Promise<string>;

export function GetUpstreamStatus():Promise<Record<string, any>>;

export function GetVersion():Promise<string>;

export function IsStratumRunning():Promise<boolean>;

export function OnStartup(arg1:context.Context):Promise<void>;

export function ReconnectMiners():Promise<Record<string, any>>;

export function ScanForMiners():Promise<Array<miner.DiscoveredMiner>>;

export function SetHost(arg1:appcore.AppHost):Promise<void>;

export function SetLogLevel(arg1:string):Promise<void>;

export function ShowWindow():Promise<void>;

export function Shutdown():Promise<void>;

export function StartStratum():Promise<void>;

export function StopStratum():Promise<void>;

export function TestNodeConnection(arg1:string,arg2:number,arg3:string,arg4:string,arg5:boolean):Promise<Record<string, any>>;

export function TestUpstreamConnection(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function UpdateConfig(arg1:config.Config):Promise<void>;

export function ValidateAddress(arg1:string,arg2:string):Promise<Record<string, any>>;
