// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyUpdate() {
  return window['go']['appcore']['App']['ApplyUpdate']();
}

export function CheckForUpdate() {
  return window['go']['appcore']['App']['CheckForUpdate']();
}

export function ClearRejectedShares() {
  return window['go']['appcore']['App']['ClearRejectedShares']();
}

export function ClearStatistics() {
  return window['go']['appcore']['App']['ClearStatistics']();
}

export function CompactDatabase() {
  return window['go']['appcore']['App']['CompactDatabase']();
}

export function ConfigureMiner(arg1) {
  return window['go']['appcore']['App']['ConfigureMiner'](arg1);
}

export function ConnectNode() {
  return window['go']['appcore']['App']['ConnectNode']();
}

export function DetectNode(arg1) {
  return window['go']['appcore']['App']['DetectNode'](arg1);
}

export function GetCoinList() {
  return window['go']['appcore']['App']['GetCoinList']();
}

export function GetConfig() {
  return window['go']['appcore']['App']['GetConfig']();
}

export function GetDashboardStats() {
  return window['go']['appcore']['App']['GetDashboardStats']();
}

export function GetDatabaseInfo() {
  return window['go']['appcore']['App']['GetDatabaseInfo']();
}

export function GetFleetOverview() {
  return window['go']['appcore']['App']['GetFleetOverview']();
}

export function GetHashrateHistory(arg1) {
  return window['go']['appcore']['App']['GetHashrateHistory'](arg1);
}

export function GetMinerHashrateHistory(arg1) {
  return window['go']['appcore']['App']['GetMinerHashrateHistory'](arg1);
}

export function GetMiners() {
  return window['go']['appcore']['App']['GetMiners']();
}

export function GetMiningMode() {
  return window['go']['appcore']['App']['GetMiningMode']();
}

export function GetNodeStatus() {
  return window['go']['appcore']['App']['GetNodeStatus']();
}

export function GetProxyDiagnostics() {
  return window['go']['appcore']['App']['GetProxyDiagnostics']();
}

export function GetRecentLogs(arg1) {
  return window['go']['appcore']['App']['GetRecentLogs'](arg1);
}

export function GetStratumURL() {
  return window['go']['appcore']['App']['GetStratumURL']();
}

export function GetUpstreamStatus() {
  return window['go']['appcore']['App']['GetUpstreamStatus']();
}

export function GetVersion() {
  return window['go']['appcore']['App']['GetVersion']();
}

export function IsStratumRunning() {
  return window['go']['appcore']['App']['IsStratumRunning']();
}

export function OnStartup(arg1) {
  return window['go']['appcore']['App']['OnStartup'](arg1);
}

export function ReconnectMiners() {
  return window['go']['appcore']['App']['ReconnectMiners']();
}

export function ScanForMiners() {
  return window['go']['appcore']['App']['ScanForMiners']();
}

export function SetHost(arg1) {
  return window['go']['appcore']['App']['SetHost'](arg1);
}

export function SetLogLevel(arg1) {
  return window['go']['appcore']['App']['SetLogLevel'](arg1);
}

export function ShowWindow() {
  return window['go']['appcore']['App']['ShowWindow']();
}

export function Shutdown() {
  return window['go']['appcore']['App']['Shutdown']();
}

export function StartStratum() {
  return window['go']['appcore']['App']['StartStratum']();
}

export function StopStratum() {
  return window['go']['appcore']['App']['StopStratum']();
}

export function TestNodeConnection(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['appcore']['App']['TestNodeConnection'](arg1, arg2, arg3, arg4, arg5);
}

export function TestUpstreamConnection(arg1, arg2, arg3) {
  return window['go']['appcore']['App']['TestUpstreamConnection'](arg1, arg2, arg3);
}

export function UpdateConfig(arg1) {
  return window['go']['appcore']['App']['UpdateConfig'](arg1);
}

export function ValidateAddress(arg1, arg2) {
  return window['go']['appcore']['App']['ValidateAddress'](arg1, arg2);
}
